version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "DAY_30_BASE"
      POSTGRES_USER: "idris"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080